import { z } from 'zod';
import type { FormConfig } from './SubmissionForm.astro';

// Node Form Configuration
export const nodeFormConfig: FormConfig = {
  id: 'node-form',
  title: 'Submit Your Node',
  description: 'Add your Meshtastic node to the community map. Your submission will be reviewed and added via GitHub PR.',
  webhookEnvVar: 'PUBLIC_N8N_WEBHOOK_URL',
  webhookPlaceholder: 'https://your-n8n-instance.com/webhook/submit-node',
  fields: [
    {
      name: 'name',
      label: 'Node Name',
      type: 'text',
      required: true,
      placeholder: 'e.g., West Ashley Relay',
      helpText: 'A descriptive name for your node',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'e.g., Solar-powered relay on residential rooftop providing west-side coverage',
      helpText: 'Optional details about your node setup',
    },
    {
      name: 'lat',
      label: 'Latitude',
      type: 'number',
      required: true,
      gridCol: 2,
      step: '0.0001',
      min: -90,
      max: 90,
      placeholder: '32.7765',
    },
    {
      name: 'lng',
      label: 'Longitude',
      type: 'number',
      required: true,
      gridCol: 2,
      step: '0.0001',
      min: -180,
      max: 180,
      placeholder: '-80.0298',
    },
    {
      name: 'type',
      label: 'Node Type',
      type: 'select',
      required: true,
      options: [
        { value: 'client', label: 'Client (default mobile/portable)' },
        { value: 'router', label: 'Router (fixed location, routing traffic)' },
        { value: 'relay', label: 'Relay (extends network range)' },
        { value: 'solar', label: 'Solar (solar-powered fixed node)' },
      ],
    },
    {
      name: 'elevation',
      label: 'Elevation (feet)',
      type: 'number',
      min: 0,
      step: 1,
      placeholder: '35',
      helpText: 'Height above ground level (optional)',
    },
    {
      name: 'owner',
      label: 'Owner Name',
      type: 'text',
      placeholder: 'e.g., CharlieM',
      helpText: 'Your name or callsign (optional)',
    },
    {
      name: 'submitterEmail',
      label: 'Email',
      type: 'email',
      required: true,
      placeholder: 'your.email@example.com',
      helpText: 'For PR notifications (not published on site)',
    },
  ],
  schema: z.object({
    name: z.string().min(1),
    description: z.string().optional(),
    lat: z.number(),
    lng: z.number(),
    type: z.enum(['relay', 'router', 'client', 'solar']),
    elevation: z.number().optional(),
    owner: z.string().optional(),
    submitterEmail: z.string().email(),
  }),
  transformData: (formData) => ({
    name: formData.get('name'),
    description: formData.get('description') || undefined,
    lat: parseFloat(formData.get('lat') as string),
    lng: parseFloat(formData.get('lng') as string),
    type: formData.get('type'),
    elevation: formData.get('elevation') ? parseInt(formData.get('elevation') as string) : undefined,
    owner: formData.get('owner') || undefined,
    submitterEmail: formData.get('submitterEmail'),
  }),
  buildPayload: (data) => ({
    name: data.name,
    description: data.description,
    coordinates: {
      lat: data.lat,
      lng: data.lng,
    },
    type: data.type,
    elevation: data.elevation,
    active: true,
    owner: data.owner,
    lastSeen: new Date().toISOString().split('T')[0],
    submitterEmail: data.submitterEmail,
    submittedAt: new Date().toISOString(),
  }),
  successMessage: '✓ Node submitted successfully! A GitHub PR will be created for review. You\'ll receive updates at your email address.',
  disclaimerText: 'By submitting, you agree that your node information will be publicly displayed on this website.',
};

// Guide Form Configuration
export const guideFormConfig: FormConfig = {
  id: 'guide-form',
  title: 'Submit a Guide',
  description: 'Share your Meshtastic knowledge with the community. Your guide will be reviewed and added via GitHub PR.',
  webhookEnvVar: 'PUBLIC_N8N_GUIDES_WEBHOOK_URL',
  webhookPlaceholder: 'https://your-n8n-instance.com/webhook/submit-guide',
  fields: [
    {
      name: 'title',
      label: 'Guide Title',
      type: 'text',
      required: true,
      placeholder: 'e.g., Setting Up Solar Power for Your Node',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      required: true,
      rows: 2,
      placeholder: 'Brief summary of what the guide covers',
    },
    {
      name: 'content',
      label: 'Guide Content',
      type: 'textarea',
      required: true,
      rows: 12,
      placeholder: 'Write your guide in Markdown format. Use ## for headings, - for lists, **bold**, *italic*, etc.',
      helpText: 'Use Markdown formatting (headers, lists, code blocks, etc.)',
      className: 'font-mono text-sm',
    },
    {
      name: 'category',
      label: 'Category',
      type: 'select',
      required: true,
      placeholder: 'Select a category...',
      options: [
        { value: 'getting-started', label: 'Getting Started' },
        { value: 'hardware', label: 'Hardware' },
        { value: 'software', label: 'Software' },
        { value: 'network', label: 'Network' },
        { value: 'troubleshooting', label: 'Troubleshooting' },
      ],
    },
    {
      name: 'difficulty',
      label: 'Difficulty Level',
      type: 'select',
      required: true,
      placeholder: 'Select difficulty...',
      options: [
        { value: 'beginner', label: 'Beginner - No prior experience needed' },
        { value: 'intermediate', label: 'Intermediate - Some experience required' },
        { value: 'advanced', label: 'Advanced - Technical knowledge required' },
      ],
    },
    {
      name: 'author',
      label: 'Author Name',
      type: 'text',
      placeholder: 'Your name or callsign (optional)',
    },
    {
      name: 'prerequisites',
      label: 'Prerequisites',
      type: 'text',
      placeholder: 'e.g., Basic soldering skills, Flashed device (comma-separated)',
      helpText: 'Comma-separated list of prerequisites (optional)',
    },
    {
      name: 'submitterEmail',
      label: 'Email',
      type: 'email',
      required: true,
      placeholder: 'your.email@example.com',
      helpText: 'For PR notifications (not published on site)',
    },
  ],
  schema: z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    content: z.string().min(50),
    category: z.enum(['getting-started', 'hardware', 'software', 'network', 'troubleshooting']),
    difficulty: z.enum(['beginner', 'intermediate', 'advanced']),
    author: z.string().optional(),
    prerequisites: z.string().optional(),
    submitterEmail: z.string().email(),
  }),
  transformData: (formData) => ({
    title: formData.get('title'),
    description: formData.get('description'),
    content: formData.get('content'),
    category: formData.get('category'),
    difficulty: formData.get('difficulty'),
    author: formData.get('author') || undefined,
    prerequisites: formData.get('prerequisites') || undefined,
    submitterEmail: formData.get('submitterEmail'),
  }),
  buildPayload: (data) => ({
    ...data,
    prerequisites: data.prerequisites
      ? data.prerequisites.split(',').map((p: string) => p.trim()).filter((p: string) => p.length > 0)
      : undefined,
    order: 999,
    submittedAt: new Date().toISOString(),
  }),
  successMessage: '✓ Guide submitted successfully! A GitHub PR will be created for review. You\'ll receive updates at your email address.',
  disclaimerText: 'By submitting, you agree that your guide will be publicly available under the site\'s license.',
};

// Meetup Form Configuration
export const meetupFormConfig: FormConfig = {
  id: 'meetup-form',
  title: 'Submit a Meetup',
  description: 'Host or propose a community meetup. Your event will be reviewed and added via GitHub PR.',
  webhookEnvVar: 'PUBLIC_N8N_MEETUPS_WEBHOOK_URL',
  webhookPlaceholder: 'https://your-n8n-instance.com/webhook/submit-meetup',
  fields: [
    {
      name: 'title',
      label: 'Event Title',
      type: 'text',
      required: true,
      placeholder: 'e.g., Monthly Mesh Meetup - February 2026',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      required: true,
      rows: 3,
      placeholder: 'Brief summary of the meetup purpose and activities',
    },
    {
      name: 'content',
      label: 'Event Details',
      type: 'textarea',
      rows: 8,
      placeholder: 'Optional: Additional details, agenda, what to bring, parking info, etc. (Markdown supported)',
      helpText: 'Use Markdown formatting for rich content (optional)',
      className: 'font-mono text-sm',
    },
    {
      name: 'date',
      label: 'Start Date',
      type: 'datetime-local',
      required: true,
      gridCol: 2,
    },
    {
      name: 'endDate',
      label: 'End Date',
      type: 'datetime-local',
      gridCol: 2,
    },
    {
      name: 'location',
      label: 'Location Name',
      type: 'text',
      required: true,
      placeholder: 'e.g., Shem Creek Park, Charleston Coffee House',
    },
    {
      name: 'address',
      label: 'Street Address',
      type: 'text',
      placeholder: '508 Mill St, Mount Pleasant, SC 29464',
      helpText: 'Full address with city and zip code (optional)',
    },
    {
      name: 'lat',
      label: 'Latitude',
      type: 'number',
      gridCol: 2,
      step: '0.0001',
      min: -90,
      max: 90,
      placeholder: '32.7765',
    },
    {
      name: 'lng',
      label: 'Longitude',
      type: 'number',
      gridCol: 2,
      step: '0.0001',
      min: -180,
      max: 180,
      placeholder: '-80.0298',
      helpText: 'GPS coordinates for map display (optional)',
    },
    {
      name: 'rsvpLink',
      label: 'RSVP Link',
      type: 'url',
      placeholder: 'https://eventbrite.com/your-event or Discord event link',
      helpText: 'Link to RSVP or get more info (optional)',
    },
    {
      name: 'maxAttendees',
      label: 'Max Attendees',
      type: 'number',
      min: 1,
      placeholder: 'e.g., 25',
      helpText: 'Venue capacity limit (optional)',
    },
    {
      name: 'submitterEmail',
      label: 'Email',
      type: 'email',
      required: true,
      placeholder: 'your.email@example.com',
      helpText: 'For PR notifications (not published on site)',
    },
  ],
  schema: z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    content: z.string().optional(),
    date: z.string().min(1),
    endDate: z.string().optional(),
    location: z.string().min(1),
    address: z.string().optional(),
    lat: z.number().optional(),
    lng: z.number().optional(),
    rsvpLink: z.string().optional(),
    maxAttendees: z.number().optional(),
    submitterEmail: z.string().email(),
  }),
  transformData: (formData) => {
    const lat = formData.get('lat') ? parseFloat(formData.get('lat') as string) : undefined;
    const lng = formData.get('lng') ? parseFloat(formData.get('lng') as string) : undefined;
    
    return {
      title: formData.get('title'),
      description: formData.get('description'),
      content: formData.get('content') || undefined,
      date: formData.get('date'),
      endDate: formData.get('endDate') || undefined,
      location: formData.get('location'),
      address: formData.get('address') || undefined,
      lat,
      lng,
      rsvpLink: formData.get('rsvpLink') || undefined,
      maxAttendees: formData.get('maxAttendees') ? parseInt(formData.get('maxAttendees') as string) : undefined,
      submitterEmail: formData.get('submitterEmail'),
    };
  },
  buildPayload: (data) => {
    const coordinates = (data.lat !== undefined && data.lng !== undefined)
      ? { lat: data.lat, lng: data.lng }
      : undefined;
    
    return {
      title: data.title,
      description: data.description,
      content: data.content,
      date: data.date,
      endDate: data.endDate,
      location: data.location,
      address: data.address,
      coordinates,
      rsvpLink: data.rsvpLink,
      maxAttendees: data.maxAttendees,
      featured: false,
      submitterEmail: data.submitterEmail,
      submittedAt: new Date().toISOString(),
    };
  },
  successMessage: '✓ Meetup submitted successfully! A GitHub PR will be created for review. You\'ll receive updates at your email address.',
  disclaimerText: 'By submitting, you agree that your meetup information will be publicly displayed on this website.',
};

// Resource Form Configuration
export const resourceFormConfig: FormConfig = {
  id: 'resource-form',
  title: 'Submit a Resource',
  description: 'Recommend a device, accessory, app, or community resource. Your submission will be reviewed and added via GitHub PR.',
  webhookEnvVar: 'PUBLIC_N8N_RESOURCES_WEBHOOK_URL',
  webhookPlaceholder: 'https://your-n8n-instance.com/webhook/submit-resource',
  fields: [
    {
      name: 'title',
      label: 'Resource Title',
      type: 'text',
      required: true,
      placeholder: 'e.g., Heltec V3 LoRa Board',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      required: true,
      rows: 3,
      placeholder: 'Brief overview of the resource',
    },
    {
      name: 'content',
      label: 'Detailed Information',
      type: 'textarea',
      rows: 8,
      placeholder: 'Optional: Detailed specs, usage tips, setup instructions, etc. (Markdown supported)',
      helpText: 'Use Markdown formatting for rich content (optional)',
      className: 'font-mono text-sm',
    },
    {
      name: 'category',
      label: 'Category',
      type: 'select',
      required: true,
      placeholder: 'Select a category...',
      options: [
        { value: 'devices', label: 'Devices' },
        { value: 'accessories', label: 'Accessories' },
        { value: 'software', label: 'Software' },
        { value: 'firmware', label: 'Firmware' },
        { value: 'community', label: 'Community' },
      ],
    },
    {
      name: 'priceRange',
      label: 'Price Range',
      type: 'text',
      placeholder: 'e.g., $25-35, Free, $100+',
      helpText: 'Approximate price range (optional)',
    },
    {
      name: 'links',
      label: 'Links',
      type: 'dynamic-array',
      helpText: 'Add links one at a time (purchase pages, documentation, download links, community resources)',
      subFields: [
        {
          name: 'label',
          label: 'Link Label',
          type: 'text',
          required: true,
          placeholder: 'e.g., Buy on Amazon',
        },
        {
          name: 'url',
          label: 'URL',
          type: 'url',
          required: true,
          placeholder: 'https://...',
        },
        {
          name: 'type',
          label: 'Link Type',
          type: 'select',
          options: [
            { value: 'purchase', label: 'Purchase' },
            { value: 'docs', label: 'Documentation' },
            { value: 'download', label: 'Download' },
            { value: 'community', label: 'Community' },
          ],
        },
      ],
    },
    {
      name: 'pros',
      label: 'Pros',
      type: 'textarea',
      rows: 3,
      placeholder: 'One pro per line:\nBuilt-in display\nLong battery life\nEasy to flash',
      helpText: 'List advantages, one per line (optional)',
    },
    {
      name: 'cons',
      label: 'Cons',
      type: 'textarea',
      rows: 3,
      placeholder: 'One con per line:\nNo GPS\nExpensive\nLimited availability',
      helpText: 'List disadvantages, one per line (optional)',
    },
    {
      name: 'image',
      label: 'Image URL',
      type: 'url',
      placeholder: 'https://example.com/image.jpg',
      helpText: 'Link to product image (optional)',
    },
    {
      name: 'submitterEmail',
      label: 'Email',
      type: 'email',
      required: true,
      placeholder: 'your.email@example.com',
      helpText: 'For PR notifications (not published on site)',
    },
  ],
  schema: z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    content: z.string().optional(),
    category: z.enum(['devices', 'accessories', 'software', 'firmware', 'community']),
    priceRange: z.string().optional(),
    links: z.array(z.object({
      label: z.string(),
      url: z.string().url(),
      type: z.string().optional(),
    })).optional(),
    pros: z.string().optional(),
    cons: z.string().optional(),
    image: z.string().optional(),
    submitterEmail: z.string().email(),
  }),
  transformData: (formData) => ({
    title: formData.get('title'),
    description: formData.get('description'),
    content: formData.get('content') || undefined,
    category: formData.get('category'),
    priceRange: formData.get('priceRange') || undefined,
    links: [], // Will be populated by dynamic array handling in form component
    pros: formData.get('pros') || undefined,
    cons: formData.get('cons') || undefined,
    image: formData.get('image') || undefined,
    submitterEmail: formData.get('submitterEmail'),
  }),
  buildPayload: (data) => {
    let links = [];
    if (data.links && Array.isArray(data.links)) {
      links = data.links.filter((link: any) => link.label && link.url);
    }
    
    const pros = data.pros
      ? data.pros.split('\n').map((p: string) => p.trim()).filter((p: string) => p.length > 0)
      : [];
    
    const cons = data.cons
      ? data.cons.split('\n').map((c: string) => c.trim()).filter((c: string) => c.length > 0)
      : [];
    
    return {
      title: data.title,
      description: data.description,
      content: data.content,
      category: data.category,
      priceRange: data.priceRange,
      links,
      pros,
      cons,
      image: data.image,
      order: 999,
      featured: false,
      submitterEmail: data.submitterEmail,
      submittedAt: new Date().toISOString(),
    };
  },
  successMessage: '✓ Resource submitted successfully! A GitHub PR will be created for review. You\'ll receive updates at your email address.',
  disclaimerText: 'By submitting, you agree that your resource recommendation will be publicly displayed on this website.',
};
